---
title: "make tables"
output: html_document
date: "2023-11-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning=FALSE, message=FALSE, echo=FALSE)
library(tidyverse)
library("survminer")
library("cmprsk")
library(rsample)
library(knitr)
library(kableExtra)
library(xtable)
source('/storage/work/yqs5519/SurvivalPlot/algorithm/CI_functions.R')
source('/storage/work/yqs5519/SurvivalPlot/algorithm/generate_data.R')
```

## Functions

```{r}
rmse = function(estimated, true) {
  y = sqrt(mean((true-estimated)^2))
  return(y)
}

mad = function(estimated, true) {
  y = mean(abs(estimated - mean(estimated)))
  return(y)
}

Wald_pair = function(stat_list, original_stat, diff_null = 0, G1, G2) {
  w = c()
  p = c()
  for (i in 1:length(stat_list)) {
    diff = stat_list[[i]][,G1] - stat_list[[i]][,G2] # bootstrap difference
    diff_var = var(diff)
    diff_hat = original_stat[i,][G1] - original_stat[i,][G2]
    diff_hat = diff_hat[1,1]
    w[i] = (diff_hat - diff_null)^2/diff_var
    p[i] = pchisq(w[i], df=1, lower.tail = F)
  }
  return(list(Wald = w, pvalue = p))
}


# sum(diff) correct
Wald_overall_sum_diff = function(stat_list, original_stat, diff_null = 0) {
  w = c()
  p = c()
  for (i in 1:length(stat_list)) {
    diff_vec = data.frame(stat_list[[i]][,1] - stat_list[[i]][,2],
                          stat_list[[i]][,1] - stat_list[[i]][,3],
                          stat_list[[i]][,2] - stat_list[[i]][,3]) %>% as.matrix()
    A = c(original_stat$group0[i] - original_stat$group1[i], 
          original_stat$group0[i] - original_stat$group2[i],
          original_stat$group1[i] - original_stat$group2[i]) %>% as.matrix() %>% t()
    covariance = cov(diff_vec)
    w[i] = A %*% MASS::ginv(covariance) %*% t(A)
    p[i] = pchisq(w[i], df=3, lower.tail = F)
  }
  return(list(Wald = w, pvalue = p))
}
```




## Get scenarios

```{r}
## scenario 1, n=200
setting1 = read.delim('/storage/work/yqs5519/SurvivalPlot/sensitivity_results1/settings.txt') ## need to change manually
location1 = setting1[29,]
location1 = gsub('/y/','/', location1) 

## scenario 2, n=200
setting3 = read.delim('/storage/work/yqs5519/SurvivalPlot/sensitivity_results5/settings.txt') ## need to change manually
location3 = setting3[29,]
location3 = gsub('/y/','/', location3) 

## scenario 3, n=200
setting5 = read.delim('/storage/work/yqs5519/SurvivalPlot/sensitivity_results13/settings.txt') ## need to change manually
location5 = setting5[29,]
location5 = gsub('/y/','/', location5) 

## scenario 4, n=200
setting7 = read.delim('/storage/work/yqs5519/SurvivalPlot/sensitivity_results6/settings.txt') ## need to change manually
location7 = setting7[29,]
location7 = gsub('/y/','/', location7) 
```

```{r}
## scenario 1, n=500
setting2 = read.delim('/storage/work/yqs5519/SurvivalPlot/sensitivity_results2/settings.txt') ## need to change manually
location2 = setting2[29,]
location2 = gsub('/y/','/', location2) 

## scenario 2, n=500
setting4 = read.delim('/storage/work/yqs5519/SurvivalPlot/sensitivity_results3/settings.txt') ## need to change manually
location4 = setting4[29,]
location4 = gsub('/y/','/', location4) 

## scenario 3, n=500
setting6 = read.delim('/storage/work/yqs5519/SurvivalPlot/sensitivity_results14/settings.txt') ## need to change manually
location6 = setting6[29,]
location6 = gsub('/y/','/', location6) 

## scenario 4, n=500
setting8 = read.delim('/storage/work/yqs5519/SurvivalPlot/sensitivity_results4/settings.txt') ## need to change manually
location8 = setting8[29,]
location8 = gsub('/y/','/', location8) 
```



## Estimation bias (MAD) (RMSE) table 

```{r}
table1 = data.frame()
Time_End_test = c()
for (j in 1:8) {
  setting = paste('setting', j, sep='') %>% get()
  location = setting[29,]
  # Time_End = setting[3,] %>% as.numeric()
  # original_stat = read.csv(paste(location, 'original_statistic.csv', sep = ''))[,-1]
  # stat_list = readRDS(paste(location, 'stat_list.rds', sep = ''))
  lambda = setting[21,] %>% as.numeric()
  rho = setting[23,] %>% as.numeric()
  beta1 = setting[13,] %>% as.numeric()
  beta2 = setting[14,] %>% as.numeric()
  beta3 = setting[15,] %>% as.numeric()
  
  ## get the right one 
  quantile = read.csv(paste(location, 'quantile.csv', sep = ''))[,-1]
  quantile2 = quantile %>% filter(quantile == 0.85)
  Time_End = round_func(quantile2$quantile_mean, mean_min = 'min') %>% as.numeric() %>% round(2)
  
  Time_End_test[j] = Time_End
    
  time_vec = seq(0.05,0.5,0.05) %>% as.numeric() %>% round(2) 
  ind = which(time_vec == Time_End)
  
  original_stat = read.csv(paste(location, 'original_statistic', ind, '.csv', sep = ''))[,-1]
  stat_list = readRDS(paste(location, 'stat_list', ind, '.rds', sep = ''))
  
  
  C_Survival_weibull1 = function(t) {
    1-exp(-lambda*(t^rho)*exp(beta1))
  }
  
  C_Survival_weibull2 = function(t) {
    1-exp(-lambda*(t^rho)*exp(beta2))
  }
  
  C_Survival_weibull3 = function(t) {
    1-exp(-lambda*(t^rho)*exp(beta3))
  }
  
  True_AUC1 = integrate(C_Survival_weibull1, 0, Time_End)$value
  True_AUC2 = integrate(C_Survival_weibull2, 0, Time_End)$value
  True_AUC3 = integrate(C_Survival_weibull3, 0, Time_End)$value
  
  true_diff12 = True_AUC1 - True_AUC2
  true_diff13 = True_AUC1 - True_AUC3
  true_diff23 = True_AUC2 - True_AUC3
  
  
  table1_temp = 
  # c(## single curve IMC0, IMC1, IMC2
  #   mad(original_stat[,1], True_AUC1), rmse(original_stat[,1], True_AUC1),
  #   mad(original_stat[,2], True_AUC2), rmse(original_stat[,2], True_AUC2),
  #   mad(original_stat[,3], True_AUC3), rmse(original_stat[,3], True_AUC3),
  #   ## pairwise IMC01, IMC02, IMC12
  #   mad(original_stat[,1] - original_stat[,2], true_diff12), rmse(original_stat[,1] - original_stat[,2], true_diff12),
  #   mad(original_stat[,1] - original_stat[,3], true_diff13), rmse(original_stat[,1] - original_stat[,3], true_diff13),
  #   mad(original_stat[,2] - original_stat[,3], true_diff23), rmse(original_stat[,2] - original_stat[,3], true_diff23))*800
    
  c(## single curve IMC0, IMC1, IMC2
    rmse(original_stat[,1], True_AUC1),
    rmse(original_stat[,2], True_AUC2),
    rmse(original_stat[,3], True_AUC3),
    ## pairwise IMC01, IMC02, IMC12
    rmse(original_stat[,1] - original_stat[,2], true_diff12),
    rmse(original_stat[,1] - original_stat[,3], true_diff13),
    rmse(original_stat[,2] - original_stat[,3], true_diff23))*30
  
  table1 = rbind(table1, table1_temp)
  
  # boxplot(original_stat[,3]- True_AUC3,  ylim = c(-0.05, 0.05))
  # if (j == 7) {
  #   print((original_stat[,3]- True_AUC3)^2 %>% mean() %>% sqrt())
  #   boxplot(original_stat[,3]- True_AUC3,  ylim = c(-0.05, 0.05))}
  # if (j == 8) {
  #   print((original_stat[,3]- True_AUC3)^2 %>% mean() %>% sqrt())
  #   boxplot(original_stat[,3]- True_AUC3,  ylim = c(-0.05, 0.05))}
}

table1 %>% xtable(digits = 2)
```


## single curve CI tables (percentile, reverse percentile)

```{r}
table2 = data.frame()
for (j in 1:8) {
  setting = paste('setting', j, sep='') %>% get()
  location = setting[29,]
  # Time_End = setting[3,] %>% as.numeric()
  # original_stat = read.csv(paste(location, 'original_statistic.csv', sep = ''))[,-1]
  # stat_list = readRDS(paste(location, 'stat_list.rds', sep = ''))
  lambda = setting[21,] %>% as.numeric()
  rho = setting[23,] %>% as.numeric()
  beta1 = setting[13,] %>% as.numeric()
  beta2 = setting[14,] %>% as.numeric()
  beta3 = setting[15,] %>% as.numeric()
  
  ## get the right one 
  quantile = read.csv(paste(location, 'quantile.csv', sep = ''))[,-1]
  quantile2 = quantile %>% filter(quantile == 0.85)
  Time_End = round_func(quantile2$quantile_mean, mean_min = 'min') %>% as.numeric() %>% round(2)
  
  time_vec = seq(0.05,0.5,0.05) %>% as.numeric() %>% round(2) 
  ind = which(time_vec == Time_End)
  
  original_stat = read.csv(paste(location, 'original_statistic', ind, '.csv', sep = ''))[,-1]
  stat_list = readRDS(paste(location, 'stat_list', ind, '.rds', sep = ''))
  
  
  C_Survival_weibull1 = function(t) {
    1-exp(-lambda*(t^rho)*exp(beta1))
  }
  
  C_Survival_weibull2 = function(t) {
    1-exp(-lambda*(t^rho)*exp(beta2))
  }
  
  C_Survival_weibull3 = function(t) {
    1-exp(-lambda*(t^rho)*exp(beta3))
  }
  
  True_AUC1 = integrate(C_Survival_weibull1, 0, Time_End)$value
  True_AUC2 = integrate(C_Survival_weibull2, 0, Time_End)$value
  True_AUC3 = integrate(C_Survival_weibull3, 0, Time_End)$value
  
  True_AUC = c(True_AUC1, True_AUC2, True_AUC3)
  
  out1 = cover_prob_single(true_stat=True_AUC, origin_stat = original_stat, stat_list, G=1, 'percentile')
  out2 = cover_prob_single(true_stat=True_AUC, origin_stat = original_stat, stat_list, G=2, 'percentile')
  out3 = cover_prob_single(true_stat=True_AUC, origin_stat = original_stat, stat_list, G=3, 'percentile')
  
  out1_r = cover_prob_single(true_stat=True_AUC, origin_stat = original_stat, stat_list, G=1, 'reverse')
  out2_r = cover_prob_single(true_stat=True_AUC, origin_stat = original_stat, stat_list, G=2, 'reverse')
  out3_r = cover_prob_single(true_stat=True_AUC, origin_stat = original_stat, stat_list, G=3, 'reverse')
  
  table2_temp = 
  c(## percentile: CP
    out1[1],
    ## reverse percentile: CP+LENGTH
    out1_r[1], out1_r[2]*0.3,
    out2[1], 
    out2_r[1], out2_r[2]*0.3, 
    out3[1],
    out3_r[1], out3_r[2]*0.3)*100
  
  table2 = rbind(table2, table2_temp)
}

table2 %>% xtable(digits = 1)
```

## pairwise CI tables

```{r}
table3 = data.frame()
for (j in 1:8) {
  setting = paste('setting', j, sep='') %>% get()
  location = setting[29,]
  # Time_End = setting[3,] %>% as.numeric()
  # original_stat = read.csv(paste(location, 'original_statistic.csv', sep = ''))[,-1]
  # stat_list = readRDS(paste(location, 'stat_list.rds', sep = ''))
  lambda = setting[21,] %>% as.numeric()
  rho = setting[23,] %>% as.numeric()
  beta1 = setting[13,] %>% as.numeric()
  beta2 = setting[14,] %>% as.numeric()
  beta3 = setting[15,] %>% as.numeric()
  
  ## get the right one 
  quantile = read.csv(paste(location, 'quantile.csv', sep = ''))[,-1]
  quantile2 = quantile %>% filter(quantile == 0.85)
  Time_End = round_func(quantile2$quantile_mean, mean_min = 'min') %>% as.numeric() %>% round(2)
  
  time_vec = seq(0.05,0.5,0.05) %>% as.numeric() %>% round(2) 
  ind = which(time_vec == Time_End)
  
  original_stat = read.csv(paste(location, 'original_statistic', ind, '.csv', sep = ''))[,-1]
  stat_list = readRDS(paste(location, 'stat_list', ind, '.rds', sep = ''))
  
  
  C_Survival_weibull1 = function(t) {
    1-exp(-lambda*(t^rho)*exp(beta1))
  }
  
  C_Survival_weibull2 = function(t) {
    1-exp(-lambda*(t^rho)*exp(beta2))
  }
  
  C_Survival_weibull3 = function(t) {
    1-exp(-lambda*(t^rho)*exp(beta3))
  }
  
  True_AUC1 = integrate(C_Survival_weibull1, 0, Time_End)$value
  True_AUC2 = integrate(C_Survival_weibull2, 0, Time_End)$value
  True_AUC3 = integrate(C_Survival_weibull3, 0, Time_End)$value
  
  True_AUC = c(True_AUC1, True_AUC2, True_AUC3)
  
  out1 = cover_prob_pair(true_stat = True_AUC, origin_stat = original_stat, 
                stat_list = stat_list, G1 = 1, G2 = 2, 'percentile')
  out2 = cover_prob_pair(true_stat = True_AUC, origin_stat = original_stat, 
                stat_list = stat_list, G1 = 1, G2 = 3, 'percentile')
  out3 = cover_prob_pair(true_stat = True_AUC, origin_stat = original_stat, 
                stat_list = stat_list, G1 = 2, G2 = 3, 'percentile')
  
  out1_r = cover_prob_pair(true_stat = True_AUC, origin_stat = original_stat, 
                stat_list = stat_list, G1 = 1, G2 = 2, 'reverse')
  out2_r = cover_prob_pair(true_stat = True_AUC, origin_stat = original_stat, 
                stat_list = stat_list, G1 = 1, G2 = 3, 'reverse')
  out3_r = cover_prob_pair(true_stat = True_AUC, origin_stat = original_stat, 
                stat_list = stat_list, G1 = 2, G2 = 3, 'reverse')
  
  table3_temp = 
  c(## percentile: CP
    out1[1],
    ## reverse percentile: CP+LENGTH
    out1_r[1], out1_r[2]*0.3,
    out2[1], 
    out2_r[1], out2_r[2]*0.3, 
    out3[1],
    out3_r[1], out3_r[2]*0.3)*100
  
  table3 = rbind(table3, table3_temp)
}

table3 %>% xtable(digits = 1)
```

## test performance (type1 and power) 

```{r}
table4 = data.frame()
for (j in 1:8) {
  setting = paste('setting', j, sep='') %>% get()
  location = setting[29,]
  # Time_End = setting[3,] %>% as.numeric()
  # original_stat = read.csv(paste(location, 'original_statistic.csv', sep = ''))[,-1]
  # stat_list = readRDS(paste(location, 'stat_list.rds', sep = ''))
  
  ## get the right one 
  quantile = read.csv(paste(location, 'quantile.csv', sep = ''))[,-1]
  quantile2 = quantile %>% filter(quantile == 0.85)
  Time_End = round_func(quantile2$quantile_mean, mean_min = 'min') %>% as.numeric() %>% round(2)
  
  time_vec = seq(0.05,0.5,0.05) %>% as.numeric() %>% round(2) 
  ind = which(time_vec == Time_End)
  
  original_stat = read.csv(paste(location, 'original_statistic', ind, '.csv', sep = ''))[,-1]
  stat_list = readRDS(paste(location, 'stat_list', ind, '.rds', sep = ''))
  
  
  test = Wald_pair(stat_list, original_stat, diff_null = 0, G1 = 1, G2 = 2)
  power01 = mean(test$pvalue<=0.05)
  
  test = Wald_pair(stat_list, original_stat, diff_null = 0, G1 = 1, G2 = 3)
  power02 = mean(test$pvalue<=0.05)
  
  test = Wald_pair(stat_list, original_stat, diff_null = 0, G1 = 2, G2 = 3)
  power12 = mean(test$pvalue<=0.05)
  
  test = Wald_overall_sum_diff(stat_list, original_stat, diff_null = 0)
  power_overall = mean(test$pvalue<=0.05)
  
  table4_temp = 
  c(power01, power02, power12, power_overall)*100
  
  table4 = rbind(table4, table4_temp)
}

table4 %>% xtable(digits = 1)
```

